name = "StreetCars"
uuid = "ae9a6d0b-adf0-4a83-9ac4-3ad2b2ae29bf"
authors = ["Zachary Zhang <zakzo1212@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
HashCode2014 = "0.1"
PythonCall = "0.9"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
